# Generated by Django 5.0.3 on 2024-03-13 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('email', models.EmailField(help_text='Enter your email address', max_length=254, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')], verbose_name='Email')),
                ('name', models.CharField(help_text='Enter your full name', max_length=128, verbose_name='Full name')),
                ('expectation', models.TextField(blank=True, help_text='What is your expectation from joining Provinear?', null=True, verbose_name='Expectation')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
            ],
            options={
                'verbose_name': 'Wait List',
                'verbose_name_plural': 'Wait Lists',
                'db_table': 'waitlist',
            },
        ),
    ]
