# Generated by Django 5.0.3 on 2024-03-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlist',
            old_name='name',
            new_name='full_name',
        ),
    ]
