# Generated by Django 5.0.3 on 2024-04-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='expectation',
        ),
        migrations.AddField(
            model_name='waitlist',
            name='interested_in_buying',
            field=models.BooleanField(default=True, help_text='Are you interested in buying on Provinear?', verbose_name='Interested in Buying'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='interested_in_selling',
            field=models.BooleanField(default=True, help_text='Are you interested in selling on Provinear?', verbose_name='Interested in Selling'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='receive_updates',
            field=models.BooleanField(blank=True, default=False, help_text='Receive updates and notification from Provinear?', verbose_name='Receive updates'),
        ),
    ]
